[package]
name = "hns-header-snapshot-exporter"
version = "0.1.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"

[workspace]

[dependencies]
hns-chain = { package = "hns-browser-chain", version = "=0.2.1", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "69e60d7bfce368d7d23c6c901946f02b173f00c4" }
hns-core = { package = "hns-browser-primitives", version = "=0.2.1", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "69e60d7bfce368d7d23c6c901946f02b173f00c4" }
hns-p2p = { package = "hns-browser-p2p", version = "=0.2.1", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "69e60d7bfce368d7d23c6c901946f02b173f00c4" }
hns-sync = { package = "hns-browser-sync", version = "=0.2.1", git = "https://github.com/handshake-rs/hns-dane-engine.git", rev = "69e60d7bfce368d7d23c6c901946f02b173f00c4" }
